// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsspifbdaqwclzutcpck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc3BpZmJkYXF3Y2x6dXRjcGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MDkzNDEsImV4cCI6MjA1NDI4NTM0MX0.DLyD3vfyxptthl_L-W3rG_R0mW4ELOyX4iZbp4Cfxos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);